Refactor kuba
Frendzlu/beerbender pull request #2
Opened 2022-07-24 18:41 UTC by JK2Kgit

Mega refactor prosze approve z grzeczności (dawać approve mendy)

2022-07-24 22:34 UTC, Frendzlu requested changes
przejrzyj se komentarze pls @JK2Kgit

2022-07-24 22:34 UTC, Frendzlu commented on package.json
> +    "pixi.js": "^5.0.0-rc"
nie usunęliśmy tego?

2022-07-24 22:34 UTC, Frendzlu commented on src/Cell.ts
> +	sidesInternal: [boolean, boolean, boolean, boolean] // bottom end top start
change to internalSides

2022-07-24 22:34 UTC, Frendzlu commented on src/Room.ts
> +  constructor(startFloor: number, endFloor: number, startPos: number, endPos: number, cellsOnFloor: number) {
change `cellsOnFloor` to `startFloorCells`

2022-07-24 22:34 UTC, Frendzlu commented on src/Room.ts
> +  constructor(floorAmount: number, worldOptions: FloorOptions, cells: Cell[][]) {
`worldOptions` nie powinny być typu `FloorOptions`

2022-07-24 22:34 UTC, Frendzlu commented on src/Room.ts
> +    roomLoop:
?

2022-07-24 22:34 UTC, Frendzlu commented on src/Room.ts
> +    roomLoop:
nie dało by się jakoś lepiej tego zrobić?

2022-07-24 22:34 UTC, Frendzlu commented on src/Room.ts
> +        let cellsFloor = this.cells[i].length
`cellsFloor` na `floorCells`

2022-07-24 22:34 UTC, Frendzlu commented on src/World.ts
> +export interface FloorOptions {
może `CellOptions`?

2022-07-24 22:34 UTC, Frendzlu commented on src/World.ts
> +			let maxCellsOnFloorExact = ((i*2*Math.PI)/this.worldOptions.minimalCellSize)
kiepska nazwa, co ma przekazywać?

2022-07-24 22:34 UTC, Frendzlu commented on src/World.ts
> +			let maxCellsOnFlorCapped = this.worldOptions.cellNumberMultiplier**pow
kiepska nazwa, co ma przekazywać?

2022-07-24 22:36 UTC, JK2Kgit commented on package.json
> +    "pixi.js": "^5.0.0-rc"
Yyy nani

2022-07-24 22:36 UTC, JK2Kgit commented on src/Cell.ts
> +	sidesInternal: [boolean, boolean, boolean, boolean] // bottom end top start
... ok 
Rly?

2022-07-24 22:37 UTC, JK2Kgit commented on src/Room.ts
> +  constructor(floorAmount: number, worldOptions: FloorOptions, cells: Cell[][]) {
Racja zapomniałem zrobić rename typu zmienię

2022-07-24 22:37 UTC, JK2Kgit commented on src/Room.ts
> +    roomLoop:
Co jest nie tak z named loop jakby nie widzę problemu
Zaproponuj lepsze rozwiązanie

2022-07-24 22:38 UTC, JK2Kgit commented on src/Room.ts
> +        let cellsFloor = this.cells[i].length
... ok 
Czepiasz sie szczegółów

2022-07-24 22:38 UTC, JK2Kgit commented on src/Room.ts
> +  constructor(startFloor: number, endFloor: number, startPos: number, endPos: number, cellsOnFloor: number) {
Ok

2022-07-24 22:38 UTC, JK2Kgit commented on src/World.ts
> +export interface FloorOptions {
WorldOptions

2022-07-24 22:39 UTC, Frendzlu commented on src/Room.ts
> +        let cellsFloor = this.cells[i].length
tak :v

2022-07-24 22:39 UTC, JK2Kgit commented on src/World.ts
> +			let maxCellsOnFloorExact = ((i*2*Math.PI)/this.worldOptions.minimalCellSize)
Ile by się zmieściło pokoju gdybyśmy nie ogarniczali się do tego że nad każdym pokojem ma być 1 lub c pokoji
Nie mam pomysłu na lepszą

2022-07-24 22:40 UTC, JK2Kgit commented on src/World.ts
> +			let maxCellsOnFlorCapped = this.worldOptions.cellNumberMultiplier**pow
To co wyżej tylko że ograniczone do 1 lub c pokoji

2022-07-24 22:42 UTC, JK2Kgit commented
Przejrzałem to są proste poprawki
PS
Prócz dodania lock do .gitignore trzeba by go też usunąć z git

2022-07-24 22:51 UTC, Frendzlu commented on src/World.ts
> +			let maxCellsOnFloorExact = ((i*2*Math.PI)/this.worldOptions.minimalCellSize)
`maxFloorCellsFromSize`?

2022-07-24 22:52 UTC, Frendzlu commented on src/World.ts
> +			let maxCellsOnFlorCapped = this.worldOptions.cellNumberMultiplier**pow
`maxFloorCellsFromMultiplier`?

2022-07-24 22:55 UTC, JK2Kgit commented on src/World.ts
> +			let maxCellsOnFlorCapped = this.worldOptions.cellNumberMultiplier**pow
To nie jest multiplayer to jest że no przy 2 
Może wyjść ze na floor mieści się 11 pokoj jednak ta zmienna ma 8 bo 8 to najwyższa potęga 2 mniejsza od 11 dla 77 to będzie 64 itp

2022-07-25 13:34 UTC, Frendzlu approved these changes
lgtm

2022-07-25 13:34 UTC, merged